export default function animationGeneration(instance, style) {
	return (
		instance.options({ speed: 20, deleteSpeed: 20, loop: true }).pause(500).move(-197).pause(1500).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).delete(9)
		.type(`<span class="${style.colorBack}">Back-End</span>`).pause(3000).delete(8)
		.type(`<span class="${style.colorBack}">Full-</span><span class="${style.colorFront}">Stack</span>`).pause(3000).delete(10)
		.type(`<span class="${style.colorFront}">Front-End</span>`).pause(3000).pause(3000).move(197)
  )
};
